// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCCWebApi.Data;

namespace TCCWebApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201209223402_CriacaoDaBaseDeDadosCulinaria")]
    partial class CriacaoDaBaseDeDadosCulinaria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TCCWebApi.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Ingrediente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Nescao",
                            UnidadeMedida = "Gramas"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Azeite",
                            UnidadeMedida = "Mililitros"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Ovo",
                            UnidadeMedida = "Unidade"
                        });
                });

            modelBuilder.Entity("TCCWebApi.Models.IngredienteProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("IngredienteProduto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredienteId = 1,
                            ProdutoId = 1,
                            Quantidade = 200m
                        },
                        new
                        {
                            Id = 2,
                            IngredienteId = 2,
                            ProdutoId = 1,
                            Quantidade = 80m
                        },
                        new
                        {
                            Id = 3,
                            IngredienteId = 3,
                            ProdutoId = 1,
                            Quantidade = 3m
                        },
                        new
                        {
                            Id = 4,
                            IngredienteId = 1,
                            ProdutoId = 2,
                            Quantidade = 200m
                        },
                        new
                        {
                            Id = 5,
                            IngredienteId = 2,
                            ProdutoId = 2,
                            Quantidade = 80m
                        },
                        new
                        {
                            Id = 6,
                            IngredienteId = 3,
                            ProdutoId = 2,
                            Quantidade = 3m
                        },
                        new
                        {
                            Id = 7,
                            IngredienteId = 1,
                            ProdutoId = 3,
                            Quantidade = 200m
                        },
                        new
                        {
                            Id = 8,
                            IngredienteId = 2,
                            ProdutoId = 3,
                            Quantidade = 80m
                        },
                        new
                        {
                            Id = 9,
                            IngredienteId = 3,
                            ProdutoId = 3,
                            Quantidade = 3m
                        });
                });

            modelBuilder.Entity("TCCWebApi.Models.ModoPreparo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ModoPreparo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Preparar nega maluca"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Preparar bolo de cenoura"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Preparar Brigadeiro"
                        });
                });

            modelBuilder.Entity("TCCWebApi.Models.ModoPreparoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ModoPreparoId")
                        .HasColumnType("int");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModoPreparoId");

                    b.ToTable("ModoPreparoItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Colocar nescau",
                            ModoPreparoId = 1,
                            Sequencia = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Colocar açucar",
                            ModoPreparoId = 1,
                            Sequencia = 2
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Colocar azeite",
                            ModoPreparoId = 1,
                            Sequencia = 3
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Colocar cenoura",
                            ModoPreparoId = 2,
                            Sequencia = 1
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Colocar trigo",
                            ModoPreparoId = 2,
                            Sequencia = 2
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Colocar azeite",
                            ModoPreparoId = 2,
                            Sequencia = 3
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Colocar leite condesado",
                            ModoPreparoId = 3,
                            Sequencia = 1
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Colocar nescau",
                            ModoPreparoId = 3,
                            Sequencia = 2
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Colocar margarina",
                            ModoPreparoId = 3,
                            Sequencia = 3
                        });
                });

            modelBuilder.Entity("TCCWebApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<int>("ModoPreparoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModoPreparoId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Nega maluca",
                            ModoPreparoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Bolo cenoura",
                            ModoPreparoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Brigadeiro",
                            ModoPreparoId = 3
                        });
                });

            modelBuilder.Entity("TCCWebApi.Models.IngredienteProduto", b =>
                {
                    b.HasOne("TCCWebApi.Models.Ingrediente", "Ingrediente")
                        .WithMany("IngredientesProdutos")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCCWebApi.Models.Produto", "Produto")
                        .WithMany("IngredientesProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TCCWebApi.Models.ModoPreparoItem", b =>
                {
                    b.HasOne("TCCWebApi.Models.ModoPreparo", "ModoPreparo")
                        .WithMany("ModoPreparoItems")
                        .HasForeignKey("ModoPreparoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModoPreparo");
                });

            modelBuilder.Entity("TCCWebApi.Models.Produto", b =>
                {
                    b.HasOne("TCCWebApi.Models.ModoPreparo", "ModoPreparo")
                        .WithMany("Produtos")
                        .HasForeignKey("ModoPreparoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModoPreparo");
                });

            modelBuilder.Entity("TCCWebApi.Models.Ingrediente", b =>
                {
                    b.Navigation("IngredientesProdutos");
                });

            modelBuilder.Entity("TCCWebApi.Models.ModoPreparo", b =>
                {
                    b.Navigation("ModoPreparoItems");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("TCCWebApi.Models.Produto", b =>
                {
                    b.Navigation("IngredientesProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
